feat(integrate): workflow dependency

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,10 +2,30 @@ name: Publish Workflow
 
 on:
   workflow_dispatch:
+    inputs:
+      force_fail:
+        description: "Set to 'true' to force the workflow to fail"
+        required: true
+        default: "false"
+        type: string
 
 jobs:
+  force-fail:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check input and force failure if needed
+        run: |
+          echo "Checking input..."
+          if [ "${{ github.event.inputs.force_fail }}" = "true" ]; then
+            echo "Input is true. Forcing the workflow to fail."
+            exit 1
+          else
+            echo "Input is false. Workflow will succeed."
+          fi
+
   deploy:
     uses: ./.github/workflows/deploy-storybook.yml
+    needs: publish
     with:
       checkout_branch: 'main'
     permissions:
